# Generated by Django 3.2.6 on 2021-08-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='Answer',
        ),
        migrations.AlterModelTable(
            name='marks_of_user',
            table='Marks_Of_Users',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='Quiz',
        ),
    ]
